version: '3.8'

services:
  bot:
    build: .
    environment:
      - MM_URL=${MM_URL}
      - MM_TOKEN=${MM_TOKEN}
    depends_on:
      - tarantool
    restart: unless-stopped

  tarantool:
    image: tarantool/tarantool:2.10
    ports:
      - "3301:3301"
    volumes:
      - tarantool_data:/var/lib/tarantool
    environment:
      - TARANTOOL_USER=admin
      - TARANTOOL_PASSWORD=password
    command: tarantool /opt/tarantool/init.lua

volumes:
  tarantool_data: