version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TARANTOOL_HOST=tarantool
      - MATTERMOST_BOT_TOKEN=${MATTERMOST_BOT_TOKEN}
      - MATTERMOST_BOT_ID=${MATTERMOST_BOT_ID}
    depends_on:
      - tarantool
    restart: unless-stopped

  tarantool:
    image: tarantool/tarantool:2.10
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    restart: unless-stopped